<a href="https://colab.research.google.com/github/atulpatil2228/Pw_All_Assignment/blob/main/Numpy__Pandas_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd



### 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
arr = [0,1,2,3,4,5]
np.array(arr)

array([0, 1, 2, 3, 4, 5])

2.Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [ ]:
arr = np.array([1.5, 2.6, 3.7],dtype= np.float64)


In [ ]:
if arr.dtype == np.float64:

  print("Yes it is Ture")
else:
  print("NO its False")

Yes it is Ture


 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
l = [2+3j,4+5j,7+2j]
arr = np.array(l,dtype =np.complex128 )
print((repr)(arr))

array([2.+3.j, 4.+5.j, 7.+2.j])


4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
arr = [0,1,2,3,4,5] ### form 1st question
arr1 = np.array(arr,dtype=np.float32)
arr1

array([0., 1., 2., 3., 4., 5.], dtype=float32)

 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

In [ ]:
l = [0,1,2,3,4,5]
arr= np.array(l,dtype=np.float64)
arr

array([0., 1., 2., 3., 4., 5.])

In [ ]:
arr2 = np.array(arr,dtype= np.float32)
arr2

array([0., 1., 2., 3., 4., 5.], dtype=float32)

 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type

In [ ]:
def array_attributes(arr):
  return arr.shape,arr.size,arr.dtype

arr = np.array([1,2,3,4,5])
shape, size, dtype = array_attributes(arr)

In [ ]:
print(shape)

(5,)


In [ ]:
print(size)

5


In [ ]:
print(arr.dtype)

int64


7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
def array_dimension(arr):
  return arr.ndim

In [ ]:
def array_dimension(arr):
    return arr.ndim


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array_dimension(arr1))
print(array_dimension(arr2))
print(array_dimension(arr3))


1
2
3


 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [ ]:
def item_size_info (arr):
  return arr.nbytes ,arr.size

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(item_size_info(arr1))
print(item_size_info(arr2))
print(item_size_info(arr3))

(24, 3)
(48, 6)
(64, 8)


 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [ ]:
def array_strides(arr):
  return arr.strides
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array_strides(arr1))
print(array_strides(arr2))
print(array_strides(arr3))

(8,)
(24, 8)
(32, 16, 8)


10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [ ]:
def shape_stride_relationship(arr):
  return arr.shape,arr.strides
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(shape_stride_relationship(arr1))
print(shape_stride_relationship(arr2))
print(shape_stride_relationship(arr3))


((3,), (8,))
((2, 3), (24, 8))
((2, 2, 2), (32, 16, 8))


11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [ ]:
def create_zeros_array(n):
  return np.zeros(n)



print(create_zeros_array(9))

print(create_zeros_array(8))



[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]


12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols

In [ ]:
def create_ones_matrix(rows ,coloumns ):
  return np.ones((rows,coloumns))

create_ones_matrix(3,3)



array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
create_ones_matrix(3,3).ndim

2

13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.
`

In [ ]:
def generate_range_array(start,stop,step):
  return np.arange(start,stop,step)

print(generate_range_array(0,10,2))



[0 2 4 6 8]


14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [ ]:
##To generate num equally spaced values including both start and stop, you should use np.linspace()
#num is the number of equally spaced values to generate between start and stop, inclusive.
def generate_linear_space(start, stop,num):
  return np.linspace(start, stop,num)

print(generate_linear_space(0,20,3))



[ 0. 10. 20.]


15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`

In [ ]:
def create_identity_matrix (n):
  return np.eye(n)

print(create_identity_matrix(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


16. Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
def python_list_to_array(lst):
  return np.array(lst)

print(python_list_to_array([1,2,3,4]))

[1 2 3 4]


17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data

In [ ]:
l = [1,2,3,4,5,6]
arr = np.array(l)

veiw_arr = arr.view()

print(arr)
print(veiw_arr)


[1 2 3 4 5 6]
[1 2 3 4 5 6]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis

In [ ]:
def takes_two_arrays(a,b,axis = 0):
  return np.concatenate ( (np.array(a) ,np.array(b)), axis = axis)

a =[1,2,3,4]
b = [5,6,7,8]
takes_two_arrays(a,b,axis = 0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a_2d = np.array(a).reshape(1, 4)
b_2d = np.array(b).reshape(1, 4)

takes_two_arrays(a_2d,b_2d,axis = 1)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.

concatenate`.

In [ ]:
l = [1,2,3,4]
arr1= np.array(l).reshape(1,4)

m =[5,8,9]
arr2= np.array(m).reshape(1,3)

np.concatenate((arr1,arr2),axis=1)





array([[1, 2, 3, 4, 5, 8, 9]])

In [ ]:
## 1d
l = [1,2,3,4]
arr1= np.array(l)

m =[5,8,9]
arr2= np.array(m)

np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 8, 9])

In [ ]:
### For self improvememt

| Goal                                  | Action                           |
| ------------------------------------- | -------------------------------- |
| Combine 1D arrays                     | Use `axis=0` or no axis          |
| Combine horizontally (side by side)   | Reshape to 2D, then use `axis=1` |
| Always wrap arrays in a tuple or list | Like this: `(arr1, arr2)`        |


20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
def vertically_stacks_multiple_arrays(*args):
  return np.vstack(args)

a = np.array([[1, 2]])
b = np.array([[3, 4]])

vertically_stacks_multiple_arrays(a,b)

array([[1, 2],
       [3, 4]])

21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [ ]:
def array_of_integers(a,b,step):
  return np.arange(a,b+1,step)

array_of_integers(0,10,3)



array([0, 3, 6, 9])

In [ ]:
## for myself p

| Function      | Use case                                   |
| ------------- | ------------------------------------------ |
| `np.arange`   | Use when you know the **step size**        |
| `np.linspace` | Use when you know the **number of values** |


22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [ ]:
def equally_spaced_values(a,b,step):
  return np.linspace(a,b,step)

equally_spaced_values(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [ ]:
def to_create_array(start, stop,step):
  return np.logspace(np.log(start),np.log(stop) ,step)

to_create_array(1,1000,5)

array([1.00000000e+00, 5.33259768e+01, 2.84365981e+03, 1.51640937e+05,
       8.08640109e+06])

24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [ ]:
import numpy as np
import pandas as pd

# Create a NumPy array with random integers between 1 and 100
data = np.random.randint(1, 101, size=(5, 3))

# Convert to Pandas DataFrame
df = pd.DataFrame(data, columns=['A', 'B', 'C'])

print(df)


In [ ]:
data = np.random.randint(1,101,size=(5,3))

df = pd.DataFrame(data, columns=["A","B","C"])

print(df)

    A   B   C
0   3  54  57
1   4  80  34
2  52   9  38
3  78  49  73
4  16  57  56


In [ ]:
import pandas as pd
import numpy as np

def replace_all_negatives_with_zero(df):
    return df.where(df >= 0, 0)


25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
def replace_all_negatives_with_zero(df):
  return df.where(df >= 0,0 )

In [ ]:
data = {
    "A" : [1,2,3,4,-4,-3,-55],
    "B" : [-9,23,4,9,-1,-7,-9]
}

df = pd.DataFrame(data)
df


A   B
0   1  -9
1   2  23
2   3   4
3   4   9
4  -4  -1
5  -3  -7
6 -55  -9

In [ ]:
replace_all_negatives_with_zero(df)

A   B
0  1   0
1  2  23
2  3   4
3  4   9
4  0   0
5  0   0
6  0   0

26. Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])



In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

np.int64(30)

27. Retrieve the element at index (1, 2) from the 2D NumPy array


In [ ]:
arr_2d =np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
arr_2d[1,2]

np.int64(6)

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:
m= arr>5
print(m)

[False  True False  True False  True]


In [ ]:
arr[arr>5]

array([ 8, 10,  7])

29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
arr_2d[ 0:2,1:3]
###0:2 → rows 0 and 1

### 1:3 → columns 1 and 2

array([[2, 3],
       [5, 6]])

31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array

In [ ]:
def extract_elements_specific(arr,indices):
  rows,cols = zip(*indices)##“Take the first elements of each pair and put them in rows, and the second elements in cols
  return arr[list(rows),list(cols)]

In [ ]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

In [ ]:
indices = [(0, 1), (2, 0), (1, 2)]
extract_elements_specific(arr,indices)

array([20, 70, 60])

32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [ ]:
def filters_elements(arr,threshold):
   return arr[arr>threshold]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
filters_elements(arr,2)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [ ]:
def specific_elements_from_3D(arr,x,y,z):
  return arr[x,y,z]

In [ ]:
specific_elements_from_3D(arr, [0, 1, 2], [1, 0, 2], [2, 1, 0])


array([ 5, 10, 24])

In [ ]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
## For myself

x = layer (which 3x3 slice)

y = row in that layer

z = column in that row

34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [ ]:
def returns_elements(arr,t):
  return arr[(arr< (t+2)) &( arr>(t-2)) ]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
returns_elements(arr,5)

array([4, 5, 6])

In [ ]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [ ]:
def extracts_elements_from_a_2D(arr,x,y):
  return arr[x,y]

In [ ]:
extracts_elements_from_a_2D(arr,1,2)

np.int64(60)

36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr+5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [ ]:
arr1 = np.arange(3).reshape(3,1)
arr2 =np.arange(12).reshape(3,4)

In [ ]:
arr1

array([[0],
       [1],
       [2]])

In [ ]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr1*arr2

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [ ]:
arr1 = np.arange(4)
arr2 =np.arange(12).reshape(3,4)

In [ ]:
arr1

array([0, 1, 2, 3])

In [ ]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr1+arr2

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [ ]:
arr1 = np.arange(3).reshape(3,1)
arr2 =np.arange(3).reshape(1,3)

arr1 + arr2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.


In [ ]:
arr1 = np.arange(6).reshape(2,1,3)
arr2 =np.arange(4).reshape(2,2,1)

arr1 * arr2

array([[[ 0,  0,  0],
        [ 0,  1,  2]],

       [[ 6,  8, 10],
        [ 9, 12, 15]]])

41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])





In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr= np.mean(arr, axis=0)


In [ ]:
arr

array([2.5, 3.5, 4.5])

42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print(row_max)


[3 6]


43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

col_max = np.max(arr,axis = 0)
col_max

array([4, 5, 6])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
sum_rows = np.cumsum(arr,axis = 1)
sum_rows

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [ ]:
np.sum(arr, axis=1)


array([ 6, 15])

45. In the given array, check if all elements in each column are even
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
arr

array([[2, 4, 6],
       [3, 5, 7]])

In [ ]:
np.all(arr%2==0,axis = 0)

array([False, False, False])

46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])


In [ ]:
original_array = np.array([1, 2, 3, 4, 5, 6])
original_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr = original_array.reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
input_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
def flattened_array(input_matrix):
  return input_matrix.flatten()

In [ ]:
flattened_array(input_matrix)

array([1, 2, 3, 4, 5, 6])

48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


array([[5, 6],
       [7, 8]])

In [ ]:
array1

array([[1, 2],
       [3, 4]])

In [ ]:
array2

array([[5, 6],
       [7, 8]])

In [ ]:
def concatenates_two_given_arrays(arr1,arr2,axis = 0):
  return np.concatenate((arr1,arr2 ),axis =  axis)

In [ ]:
concatenates_two_given_arrays(array1,array2,axis= 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
concatenates_two_given_arrays(array1,array2,axis= 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

49. Create a function that splits an array into multiple sub-arrays along a specified axis
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
def splits_an_array(arr,n,axis=0):
  return np.split(arr,n,axis = axis)


In [ ]:
splits_an_array(original_array,3,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [ ]:
splits_an_array(original_array,3,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [ ]:
def inserts_and_then_deletes_elements(arr,indices_to_insert,values_to_insert,indices_to_delete):

   arr_after_insert = np.insert(arr, indices_to_insert, values_to_insert)

   arr_after_delete = np.delete(arr_after_insert, indices_to_delete)

   return arr_after_delete





In [ ]:
original_array

array([1, 2, 3, 4, 5])

In [ ]:
result = inserts_and_then_deletes_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
result

array([ 1, 10,  4, 11,  5])

51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
arr1 = np.random.randint(1,10,size=(3,3))
arr1

array([[7, 4, 2],
       [9, 3, 5],
       [5, 6, 3]])

In [ ]:
arr2 = np.random.randint(1,10 ,size=(3,3))
arr2

array([[8, 2, 5],
       [5, 3, 8],
       [3, 4, 6]])

In [ ]:
arr1 + arr2

array([[15,  6,  7],
       [14,  6, 13],
       [ 8, 10,  9]])

52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [ ]:
arr1 = np.arange(10,1,-1).reshape(3,3)
arr1

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [ ]:
arr2 = np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2-arr1

array([[-9, -7, -5],
       [-3, -1,  1],
       [ 3,  5,  7]])

53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [ ]:
arr1 = np.random.randint(1,5,size=(3,3))
arr1

array([[4, 4, 1],
       [1, 2, 2],
       [1, 1, 1]])

In [ ]:
arr2 = np.random.randint(1,10,size=(3,3))
arr2

array([[9, 5, 9],
       [9, 1, 7],
       [3, 6, 6]])

In [ ]:
arr1*arr2

array([[36, 20,  9],
       [ 9,  2, 14],
       [ 3,  6,  6]])

54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:
arr1 = np.arange(2,10,2).reshape(2,2)
arr1

array([[2, 4],
       [6, 8]])

In [ ]:
arr2 =np.arange(1,5).reshape(2,2)
arr2

array([[1, 2],
       [3, 4]])

In [ ]:
arr1/ arr2

array([[2., 2.],
       [2., 2.]])

55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:
arr1 = np.arange(1,5).reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [ ]:
arr2 = np.arange(5,1,-1).reshape(2,2)
arr2

array([[5, 4],
       [3, 2]])

In [ ]:
np.power(arr1, arr2)

array([[ 1, 16],
       [27, 16]])

56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
np.char.count(arr,["hello"])

array([1, 0, 1, 0, 1])

In [ ]:
np.char.count(arr,["world"])

array([0, 1, 0, 0, 0])

57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])




In [ ]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
import numpy as np

def extract_uppercase(arr):
    return np.array([''.join([char for char in s if char.isupper()]) for s in arr])


arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase(arr)

print(result)


['H' 'W' 'OAI' 'GPT']


58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


In [ ]:
def replaces_occurrences_of_a_substring(arr,a,b):
  return np.char.replace(arr, 'a', 'c')

In [ ]:
result = replaces_occurrences_of_a_substring(arr,"a","c")
print(result)


['cpple' 'bcncnc' 'grcpe' 'pinecpple']


59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [ ]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [ ]:
def concatenates_strings(arr1,arr2):
  return np.char.add(arr1,arr2) ## for strings add np,char.add

In [ ]:
concatenates_strings(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
def length_the_longest_string(arr):
  return np.max(np.char.str_len(arr)) ## new concept for me

In [ ]:
length_the_longest_string(arr)

np.int64(9)

61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions

In [ ]:
l = np.random.randint(1,1000,20)

In [ ]:
l

array([209,  21, 426, 845, 838, 693, 547, 400,  79, 563, 693, 133, 538,
       491, 981,  63, 876,  17, 974, 493])

In [ ]:
np.mean(l)

np.float64(494.0)

In [ ]:
np.median(l)

np.float64(515.5)

In [ ]:

np.var(l)

np.float64(98899.9)

In [ ]:
np.std(l)

np.float64(314.48354487953736)

62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [ ]:
num = np.random.randint(1,100,50)
num

array([93, 74, 10, 61, 80, 90, 41, 62, 85, 94, 18, 65, 97, 26, 10, 50, 74,
       46, 68, 88, 90,  4, 98, 63, 39, 26, 61, 60, 13,  1, 88, 54, 56, 29,
       71, 26, 21, 72, 38, 37, 87, 91, 26, 74, 42, 42, 13, 78, 12, 33])

In [ ]:
num25 = np.percentile(num,25)
num25

np.float64(26.75)

In [ ]:
num75 = np.percentile(num,75)
num75

np.float64(77.0)

63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function

In [ ]:
arr1 = np.random.randint(1,12,4)
arr1

array([3, 9, 9, 8])

In [ ]:
arr2 = np.random.randint(1,12,4)
arr2

array([10,  8,  4,  2])

In [ ]:
np.corrcoef(arr1,arr2)

array([[ 1.        , -0.63564173],
       [-0.63564173,  1.        ]])

64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [ ]:
arr1 = np.random.randint(1,12,4).reshape(2,2)
arr1

array([[ 2, 11],
       [ 4,  4]])

In [ ]:
arr2 = np.random.randint(1,12,4).reshape(2,2)
arr2

array([[7, 3],
       [8, 6]])

In [ ]:
np.dot(arr1,arr2)

array([[102,  72],
       [ 60,  36]])

65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [ ]:
arr = np.random.randint(10,1000,50)
arr

array([660, 992, 229, 877, 118, 251, 226, 582, 834,  40, 917, 531, 254,
       181,  69, 353, 598, 878, 780, 813,  66, 332, 916,  44, 562, 992,
       944, 804, 660, 132, 533, 143, 264, 467, 518, 998, 591, 158, 336,
       739, 933, 326, 456, 669, 305, 321, 891, 489, 167, 608])

In [ ]:
arr10= np.percentile(arr,10)
arr10

np.float64(130.6)

In [ ]:
arr50= np.percentile(arr,50)
arr50

np.float64(524.5)

In [ ]:
arr90= np.percentile(arr,90)
arr90

np.float64(918.6)

In [ ]:
arr25= np.percentile(arr,25)
arr25

np.float64(251.75)

In [ ]:
arr75= np.percentile(arr,75)
arr75

np.float64(798.0)

66. Create a NumPy array of integers and find the index of a specific element.

In [ ]:
arr = np.random.randint(10,1000,9).reshape(3,3)


In [ ]:
value_to_find = arr[0, 0]
index = np.argwhere(arr == value_to_find)
print(arr)
print(value_to_find)
print(index)

[[349  39 290]
 [667 937 469]
 [177 928  51]]
349
[[0 0]]


67. Generate a random NumPy array and sort it in ascending order.

In [ ]:
arr = np.random.randint(10, 1000, 9).reshape(3, 3)
arr

array([[933, 669, 449],
       [666, 393, 260],
       [383, 345, 415]])

In [ ]:
sorted_arr = np.sort(arr,axis=None)
sorted_arr

array([260, 345, 383, 393, 415, 449, 666, 669, 933])

68. Filter elements >20  in the given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

In [ ]:
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr>20]

array([25, 42, 30])

69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

In [ ]:
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3==0]

array([12, 15])

70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[(arr>=30) & (arr<=40)]


array([30, 40])

71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])


In [ ]:
arr = np.array([1, 2, 3])
arr.dtype.byteorder


'='

'=': Native byte order (depends on your system: little-endian on most machines)

'<': Little-endian

'>': Big-endian

'|': Not applicable (e.g., for byte strings)

72. For the given NumPy array, perform byte swapping in place using `byteswap()`
arr = np.array([1, 2, 3], dtype=np.int32)

In [3]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

In [4]:
## For Studies

.byteswap() reverses the byte order of each element.

inplace=True modifies the original array.

It's useful for handling data across systems with different endianness.

73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [10]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying the original array
swapped = arr.view(arr.dtype.newbyteorder('S'))  # 'S' = swap


In [11]:
swapped

array([16777216, 33554432, 50331648], dtype='>i4')

74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()
arr = np.array([1, 2, 3], dtype=np.int32)

In [17]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Check the byte order of the array's dtype
byte_order = arr.dtype.byteorder

# If it's not native ('=') and not byte-neutral ('|'), then convert to native
if byte_order not in ('=', '|'):
    arr = arr.view(arr.dtype.newbyteorder('='))


In [18]:
print("Byte order after check:", arr.dtype.byteorder)


Byte order after check: =


75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [19]:
arr = np.array([1, 2, 3], dtype=np.int32)

In [22]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)


byte_order = arr.dtype.byteorder

byte_order






'='

76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`


In [25]:
arr1=np.random.randint(1,10,4)
arr1

array([4, 8, 4, 7])

In [27]:
copy_arr = arr1.copy()
copy_arr

array([4, 8, 4, 7])

In [28]:
copy_arr[0] = 111

In [29]:
copy_arr

array([111,   8,   4,   7])

In [32]:
print("orignal arrray:", arr1 )
print("New array:", copy_arr)

orignal arrray: [4 8 4 7]
New array: [111   8   4   7]


77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.




In [41]:
array_matrix = np.random.randint(1,10,9).reshape(3,3)
array_matrix

array([[5, 5, 4],
       [9, 5, 5],
       [2, 3, 1]])

In [42]:
 view_slice = array_matrix[0:2,1:3]

In [43]:
view_slice[0,0] = 99

In [44]:
view_slice

array([[99,  4],
       [ 5,  5]])

In [45]:
array_matrix

array([[ 5, 99,  4],
       [ 9,  5,  5],
       [ 2,  3,  1]])

In [46]:
## i observed when i changed the view_slice it also changed i array_matrix

78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [48]:
array_a = np.random.randint(1,12,12).reshape(4,3)

In [49]:
array_a

array([[ 6,  4,  2],
       [ 5,  4,  1],
       [ 6,  6,  2],
       [11,  4,  5]])

In [58]:
view_b = array_a[0:2,1:3]

In [59]:
view_b

array([[4, 2],
       [4, 1]])

In [62]:
view_b+5

array([[9, 7],
       [9, 6]])

In [63]:
array_a

array([[ 6,  4,  2],
       [ 5,  4,  1],
       [ 6,  6,  2],
       [11,  4,  5]])

In [64]:
## i observed it the main array_a doesnot change when i add +5 on the slice

79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [65]:
orig_array = np.random.randint(1,8,8).reshape(2,4)

In [66]:
orig_array

array([[2, 6, 4, 5],
       [5, 6, 3, 7]])

In [67]:
reshaped_view = orig_array.reshape(4,2)

In [68]:
reshaped_view

array([[2, 6],
       [4, 5],
       [5, 6],
       [3, 7]])

In [73]:
reshaped_view[2,1] =99

In [74]:
reshaped_view

array([[ 2,  6],
       [ 4,  5],
       [ 5, 99],
       [ 3,  7]])

In [75]:
orig_array

array([[ 2,  6,  4,  5],
       [ 5, 99,  3,  7]])

In [76]:
## i observed when i changed the reshaped_view  it also changed in orig_array

80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [77]:
data = np.random.randint(1,20,12).reshape(3,4)
data

array([[ 5, 11,  1,  1],
       [ 7,  2,  6, 19],
       [ 3,  2,  8,  1]])

In [79]:
data_copy =  data[data > 5].copy()

In [80]:
data_copy

array([11,  7,  6, 19,  8])

In [81]:
data_copy[0] = 99

In [82]:
data_copy

array([99,  7,  6, 19,  8])

In [83]:
data

array([[ 5, 11,  1,  1],
       [ 7,  2,  6, 19],
       [ 3,  2,  8,  1]])

In [84]:
## i observed it the data doesnot change when Extract a copy data_copy of elements greater than 5 , do some slicing

81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [87]:
A = np.random.randint(1,10,9).reshape(3,3)

In [88]:
A

array([[4, 3, 4],
       [8, 9, 1],
       [3, 7, 4]])

In [89]:
B = np.random.randint(11,20,9).reshape(3,3)

In [90]:
B

array([[17, 18, 11],
       [14, 18, 12],
       [13, 18, 19]])

In [91]:
A+B

array([[21, 21, 15],
       [22, 27, 13],
       [16, 25, 23]])

In [93]:
A-B

array([[-13, -15,  -7],
       [ -6,  -9, -11],
       [-10, -11, -15]])

In [94]:
B-A

array([[13, 15,  7],
       [ 6,  9, 11],
       [10, 11, 15]])

82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [95]:
C = np.random.randint(1,10,6).reshape(3,2)

In [96]:
C

array([[9, 4],
       [5, 3],
       [7, 7]])

In [97]:
D = np.random.randint(1,10,8).reshape(2,4)

In [98]:
D

array([[8, 1, 8, 7],
       [9, 7, 2, 8]])

In [103]:
np.matmul(C, D)

array([[108,  37,  80,  95],
       [ 67,  26,  46,  59],
       [119,  56,  70, 105]])

In [105]:
E  = np.random.randint(1,10,9).reshape(3,3)

In [106]:
E

array([[8, 9, 2],
       [2, 6, 8],
       [6, 9, 6]])

In [107]:
E_Transpose = E.T

In [108]:
E_Transpose

array([[8, 2, 6],
       [9, 6, 9],
       [2, 8, 6]])

84. Generate a square matrix `F` and compute its determinant.

In [109]:
F = np.random.randint(1,10,9).reshape(3,3)

In [110]:
F

array([[1, 5, 2],
       [1, 4, 6],
       [3, 4, 4]])

In [111]:
np.linalg.det(F)

np.float64(46.0)

85. Create a square matrix `G` and find its inverse

In [112]:
G = np.random.randint(1,10,9).reshape(3,3)

In [113]:
G

array([[6, 8, 3],
       [1, 4, 3],
       [3, 1, 9]])

In [114]:
np.linalg.inv(G)

array([[ 0.2       , -0.41818182,  0.07272727],
       [-0.        ,  0.27272727, -0.09090909],
       [-0.06666667,  0.10909091,  0.0969697 ]])